apiVersion: v1
kind: Service
metadata:
  name: professor-service
  labels:
    app: professor-service
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: professor-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: professor-service
  labels:
    app: professor-service
spec:
  selector:
    matchLabels:
      app: professor-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: professor-service
    spec:
      containers:
      - image: PROFESSOR_SERVICE
        resources:
          requests:
            memory: "128Mi"
            cpu: .05
          limits:
            memory: "150Mi"
            cpu: .07
        name: professor-service
        ports:
        - containerPort: 8000
          name: http
